### ISSUE TITLE
README: default YAML steps

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/buildkite#2]
```yaml
steps:
  - label: ":buildkite: Pipeline upload"
    command: buildkite-agent pipeline upload
    branches: "!gh-pages"
    agents:
      queue: "juliagpu"
```
