### ISSUE TITLE
Note to self on the "pipeline upload"

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaGPU/buildkite#22]
For posterity, here is what I did. I went to https://buildkite.com/julialang/dagger-dot-jl, and I clicked on the "Edit Steps" button. The contents looked like this originally:
```yaml
steps:
  - command: buildkite-agent pipeline upload
```

I instead changed the contents to look like this (taken from the steps for the CUDA.jl pipeline):
```yaml
steps:
  - label: ":buildkite: Pipeline upload"
    command: buildkite-agent pipeline upload
    branches: "!gh-pages"
    agents:
      queue: "juliagpu"
```
